"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { SessionUser } from "@/lib/session";
import type { AdminUserListItem } from "@/lib/types";
import { UserManagement } from "@/components/UserManagement";

type Profile = { id:string; name:string; category:string; requirements:string[]; requirementOther:string; technicalCompetencies:string; experience:string; studyType:string; educationLevel:string; shiftSystem:string; genderPreference:string; quantity:number; behaviours:string[] };
type Row = { id:string; name:string; position:string; company:string; email:string; phone:string; sector:string; sector_other?:string; company_size:string; commune:string; commune_other?:string; demand_timing:string; has_gaps:string; gap_details?:string; wants_support:string; contact_consent:string; comments?:string; created_at:string; profiles:Profile[] };

function countBy(rows: Row[], key: (r: Row) => string) { const m = new Map<string,number>(); rows.forEach(r => { const k = key(r) || "Sin respuesta"; m.set(k,(m.get(k)||0)+1); }); return [...m.entries()].map(([name,value]) => ({name,value})).sort((a,b)=>b.value-a.value); }
function Bars({ data, color = "teal" }: { data:{name:string;value:number}[]; color?:string }) { const max = Math.max(1,...data.map(d=>d.value)); return <div className="bars">{data.slice(0,8).map(d => <div className="bar-row" key={d.name}><div className="bar-label"><span>{d.name}</span><strong>{d.value}</strong></div><div className="bar-track"><span className={`bar-fill ${color}`} style={{width:`${d.value/max*100}%`}} /></div></div>)}</div>; }

export function Dashboard({ initialRows, initialUsers, user }: { initialRows: Row[]; initialUsers: AdminUserListItem[]; user: SessionUser }) {
  const router = useRouter();
  const [rows,setRows] = useState(initialRows);
  const [userCount,setUserCount] = useState(initialUsers.length);
  const [tab,setTab] = useState<"summary"|"responses"|"users">("summary");
  const [search,setSearch] = useState("");
  const [commune,setCommune] = useState("");
  const [detail,setDetail] = useState<Row|null>(null);
  const [deleting,setDeleting] = useState(false);
  const filtered = useMemo(() => rows.filter(r => (!commune || (r.commune === "Otra" ? r.commune_other : r.commune) === commune) && (!search || [r.company,r.email,r.name,r.sector,r.commune,...r.profiles.map(p=>p.name)].join(" ").toLowerCase().includes(search.toLowerCase()))),[rows,search,commune]);
  const communes = useMemo(() => [...new Set(rows.map(r => r.commune === "Otra" ? r.commune_other || "Otra" : r.commune))].sort(),[rows]);
  const totalPeople = rows.reduce((sum,r)=>sum+r.profiles.reduce((s,p)=>s+Number(p.quantity||0),0),0);
  const companiesHiring = rows.filter(r=>r.demand_timing!=="No por el momento").length;
  const topProfiles = useMemo(() => { const m = new Map<string,number>(); rows.flatMap(r=>r.profiles).forEach(p=>m.set(p.name,(m.get(p.name)||0)+Number(p.quantity||1))); return [...m.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value); },[rows]);
  const logout = async() => { await fetch("/api/auth/logout",{method:"POST"}); router.push("/auth"); router.refresh(); };
  const remove = async() => { if(!detail||deleting)return; setDeleting(true); const res=await fetch(`/api/admin/responses/${detail.id}`,{method:"DELETE"}); setDeleting(false); if(res.ok){setRows(x=>x.filter(r=>r.id!==detail.id));setDetail(null);} };
  return <div className="dashboard-shell">
    <aside className="dashboard-sidebar"><Link href="/" className="dashboard-brand"><Image src="/logo-centinela.png" width={170} height={60} alt="Centinela · Antofagasta Minerals" /><span className="mono">Programa de Empleabilidad</span></Link><nav><button className={tab==="summary"?"active":""} onClick={()=>setTab("summary")}><span>◫</span> Resumen</button><button className={tab==="responses"?"active":""} onClick={()=>setTab("responses")}><span>≡</span> Respuestas <b>{rows.length}</b></button>{user.role==="admin"&&<button className={tab==="users"?"active":""} onClick={()=>setTab("users")}><span>♙</span> Usuarios <b>{userCount}</b></button>}</nav><div className="sidebar-user"><div>{user.name}<small>{user.email}</small></div><button onClick={logout}>Salir</button></div></aside>
    <main className="dashboard-main"><header className="dashboard-top"><div><p className="mono">Panel interno</p><h1>{tab==="summary"?"Diagnóstico de empleabilidad":tab==="responses"?"Respuestas registradas":"Administración de usuarios"}</h1></div><div className="dashboard-actions"><Link href="/diagnostico" target="_blank" className="dash-ghost">Ver encuesta ↗</Link>{tab!=="users"&&<a className="dash-primary" href="/api/admin/export">Exportar CSV</a>}</div></header>
      {tab==="summary" ? <>
        <section className="metric-grid"><article><span>Respuestas totales</span><strong>{rows.length}</strong><small>Empresas participantes</small></article><article><span>Con demanda laboral</span><strong>{companiesHiring}</strong><small>{rows.length?Math.round(companiesHiring/rows.length*100):0}% del total</small></article><article><span>Personas requeridas</span><strong>{totalPeople}</strong><small>Vacantes proyectadas</small></article><article><span>Solicitan apoyo</span><strong>{rows.filter(r=>r.wants_support==="Sí").length}</strong><small>Interés en vinculación</small></article></section>
        {rows.length===0 ? <div className="dashboard-empty"><h2>Aún no hay respuestas registradas</h2><p>Cuando una empresa complete el diagnóstico, sus datos y estadísticas aparecerán aquí automáticamente.</p><Link href="/diagnostico" className="dash-primary">Abrir diagnóstico</Link></div> : <section className="chart-grid"><article className="chart-card"><div className="card-title"><div><span className="mono">Demanda territorial</span><h2>Empresas por comuna</h2></div></div><Bars data={countBy(rows,r=>r.commune==="Otra"?r.commune_other||"Otra":r.commune)} /></article><article className="chart-card"><div className="card-title"><div><span className="mono">Capital humano</span><h2>Perfiles más requeridos</h2></div></div><Bars data={topProfiles} color="terracotta" /></article><article className="chart-card"><div className="card-title"><div><span className="mono">Actividad económica</span><h2>Participación por rubro</h2></div></div><Bars data={countBy(rows,r=>r.sector==="Otro"?r.sector_other||"Otro":r.sector)} /></article><article className="chart-card"><div className="card-title"><div><span className="mono">Proyección</span><h2>Horizonte de contratación</h2></div></div><Bars data={countBy(rows,r=>r.demand_timing)} color="amber" /></article></section>}
      </> : tab==="responses" ? <section className="responses-card"><div className="response-tools"><input type="search" placeholder="Buscar por empresa, correo, comuna, rubro o perfil" aria-label="Buscar respuestas" value={search} onChange={e=>setSearch(e.target.value)} /><select value={commune} onChange={e=>setCommune(e.target.value)}><option value="">Todas las comunas</option>{communes.map(c=><option key={c}>{c}</option>)}</select><span>{filtered.length} de {rows.length}</span></div>{filtered.length===0?<div className="table-empty">Ninguna respuesta coincide con la búsqueda.</div>:<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Empresa</th><th>Comuna</th><th>Demanda</th><th>Perfiles</th><th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleDateString("es-CL")}</td><td><strong>{r.company}</strong><small>{r.email}</small></td><td>{r.commune==="Otra"?r.commune_other:r.commune}</td><td><span className={`status ${r.demand_timing==="No por el momento"?"neutral":"positive"}`}>{r.demand_timing}</span></td><td>{r.profiles.length} · {r.profiles.reduce((s,p)=>s+Number(p.quantity||0),0)} pers.</td><td><button onClick={()=>setDetail(r)}>Ver detalle</button></td></tr>)}</tbody></table></div>}</section> : <UserManagement initialUsers={initialUsers} currentUserId={user.id} onUserCreated={()=>setUserCount((count)=>count+1)} />}
    </main>
    {detail&&<div className="detail-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><section className="detail-modal" role="dialog" aria-modal="true"><header><div><span className="mono">Registro completo</span><h2>{detail.company}</h2><p>{new Date(detail.created_at).toLocaleString("es-CL")}</p></div><button aria-label="Cerrar" onClick={()=>setDetail(null)}>×</button></header><div className="detail-body"><div className="detail-grid"><div><small>Contacto</small><strong>{detail.name}</strong><p>{detail.position}<br/>{detail.email}<br/>{detail.phone}</p></div><div><small>Empresa</small><strong>{detail.sector==="Otro"?detail.sector_other:detail.sector}</strong><p>{detail.company_size}<br/>{detail.commune==="Otra"?detail.commune_other:detail.commune}</p></div><div><small>Demanda</small><strong>{detail.demand_timing}</strong><p>Brechas: {detail.has_gaps}<br/>Apoyo: {detail.wants_support}<br/>Contacto: {detail.contact_consent}</p></div></div>{detail.gap_details&&<div className="detail-note"><small>Brechas identificadas</small><p>{detail.gap_details}</p></div>}{detail.comments&&<div className="detail-note"><small>Comentarios</small><p>{detail.comments}</p></div>}<h3>Perfiles demandados</h3>{detail.profiles.length?detail.profiles.map(p=><article className="detail-profile" key={p.id}><div><strong>{p.name}</strong><span>{p.category}</span></div><b>{p.quantity} pers.</b><p>{p.technicalCompetencies}</p><small>{[p.experience,p.studyType,p.educationLevel,p.shiftSystem].filter(Boolean).join(" · ")}</small></article>):<p className="no-profile">Sin perfiles informados.</p>}</div><footer><button className="dash-ghost" onClick={()=>setDetail(null)}>Cerrar</button>{user.role==="admin"&&<button className="delete-btn" onClick={remove} disabled={deleting}>{deleting?"Eliminando…":"Eliminar respuesta"}</button>}</footer></section></div>}
  </div>;
}
